version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    enviroment:
      MYSQL_DATABASE: flashcards
      MYSQL_USER: ozan
      MYSQL_PASSWORD: ozanozan123
      MYSQL_ROOT_PASSWORD: password